### ISSUE TITLE
Trading Review Feedback

### ISSUE THREAD

**Issue by JohnDanz** [AugurProject/augur-ui#2041]
Hello Augur Community,

We are currently in the process of updating the information seen on the trading page when you click on `review` for a trade you intend to make. Currently that looks something like this:

<img width="418" alt="screen shot 2018-07-19 at 11 39 12 am" src="https://user-images.githubusercontent.com/10524630/42957475-6a1a2ad4-8b48-11e8-9993-9b186ab86e23.png">

We are looking to improve the information shown here in an attempt to make it more clear to users what they stand to gain/lose for the trade. An early mock up of an improved view is pictured here:

![new review 1](https://user-images.githubusercontent.com/10524630/42957540-9eea0590-8b48-11e8-911c-db85b192109f.png)

In this above case, there are 2 orders on the book, one for 1 share at .4 and 1 for 1 share at .5. Assuming the orderbook is the same by the time this trade is processed the est cost of that trade would be .9 ETH, however the maximum cost of this trade is 1 ETH because if that .4 order is gone by the time you make your trade, it's going to cost you 1 ETH to either take 2 orders at .5 or place an order to sell 2 shares at .5. You can see these values reflected in the potential profit and loss here, you stand to lose a maximum of 1 ETH (if you had to spend 1 ETH to place an order for 2 shares at .5) but you stand to gain 1 ETH in this case as well (2 shares purchased for .5 Each, if you win, would be worth 1 ETH each, you paid 1 ETH for them, you get back 2 ETH, thats a gain of 1 ETH - fees).

Our goal is to provide a clear understanding of how the trade might effect the user.

_**Here are some questions for the community:**_

- **Is this information clear to you?**
- **Would you want to see other information?**
- **Do you have a suggestion for how you would like to see this information laid out?**

**Comment by page1** [comment]
Hi @JohnDanz 
I was initially confused looking over UI2 because the estimated cost didn't make sense with the information I had available. 

After reading your description I do understand what's going on here.

Due to this initial confusion, if both Estimated and Max costs are going to be included I think they both needs a little "?" blurb to help users understand what the estimate is based off of.

To play devils advocate with regards to Estimated & Max costs: 
- What happens to the cost & estimate if you are closing a position or reversing a position?
- Possibly only the Max cost is needed. The estimate may be too high or too low due to moving market conditions. The final cost should be made easily findable somewhere after the fill details are known.
- Adding an additional number to an already highly numerate view, may overload average users.
- Estimated cost provides conflicting numbers vs Potential Profit & Loss
- My verdict would be to stick to the concrete value of Max Cost. Especially since this is a distributed application where we can't know for sure what the market conditions will be when the order is filled.

Some other points of observation:
- With respect to potential profit and potential loss, isn't the potential loss always 100%? And therefore only the potential profit is needed? 
- Potential percent profit works great for me, but others might want more of an odds type of value. I'm not sure what is typical on other betting platforms.
- I think it might be more intuitive to have the confirm buy and sell buttons in green and red.

Thank you for seeking input, and feel free to disregard portions of my comments that are out of scope or not popular opinion. I'm excited to see how things shape up.

**Comment by JohnDanz** [comment]
@page1 thanks for the feed back! These are some great points!

to answer your questions:
`What happens to the cost & estimate if you are closing a position or reversing a position?`
the est cost will still try to show you best case scenario given current book.

Max cost would show the maximum amount of ETH and shares dumped to make that trade if the book isn't the same/worse when your transaction gets processed.

`With respect to potential profit and potential loss, isn't the potential loss always 100%? And therefore only the potential profit is needed?` 

For the most part yes, but if you had Shares and you are closing your position the potential loss is 0 and 0% because you only stand to gain from turning in your shares/trading away shares. The trade itself is "cashing out" basically so you can't "lose" ETH if you plan to turn in your shares for ETH. So it makes sense to just show them both for clarity reasons.

**Comment by page1** [comment]
@JohnDanz Some more food for thought

Example scenario starting with empty market:
1. Place order below market for 1 share at 25% - Max cost = 0.25 eth
2. Other party places order to open position by selling 1 share at 25% - Max cost = 0.75 eth
3. Place order above market to sell 1 share at 75% - Estimated proceeds = 0.75 eth, Max cost = 0.25 eth
4. Place order above market to sell 1 share at 50% - Estimated proceeds = 0.5 eth, Max cost = 0.5 eth
5. Other party places order to open position by buying 2 shares at 75% - Estimated cost = 1.25 eth, Max cost = 1.5 eth

In this scenario, orders 1, 3, 4 are placed by me, and orders 2 & 5 are placed by 2 separate other parties.

Observations:
- Avoid the confusing use of shares in the estimated/max cost/proceeds verbiage. Shares are a unit of volume to be bought and sold, never "costed" or "proceeded" (i'm sure there is a better word for what I'm implying) 
- Estimated Proceeds denotes the expectation that shares will be sold and free up funds to place new bets
- Max "cost" is always a "cost" and always denoted in eth because you might be opening a new position. (Sync issues, or placing a second order that closes the position prior to the first order... making the first order open a new position)

**Comment by Chwy5** [comment]
Avoid the confusing use of shares in the estimated/max cost/proceeds verbiage. Shares are a unit of volume to be bought and sold, never "costed" or "proceeded" (i'm sure there is a better word for what I'm implying)
Estimated Proceeds denotes the expectation that shares will be sold and free up funds to place new bets
Max "cost" is always a "cost" and always denoted in eth because you might be opening a new position. (Sync issues, or placing a second order that closes the position prior to the first order... making the first order open a new position)
I personally totally  agree with this approach - from a trading standpoint, this is how I would expect to see.....Playing Devil's advocate - on blockchain etherscan doesn't always show the transaction amount to match this and depending on the users position the transaction amount may only display the partial value because of shares owned.
