### ISSUE TITLE
account summary: three columns should be even width 

### ISSUE THREAD

**Issue by bthaile** [AugurProject/augur-ui#2778]
All three account summary columns should be and maintain same width.

If you resize the browser you can see they don't maintain same width.

**Comment by phoebemirman** [comment]
<img width="1357" alt="Screen Shot 2019-03-19 at 12 58 23 PM" src="https://user-images.githubusercontent.com/6775839/54637896-f9c34180-4a46-11e9-91c2-bedf4135ed68.png">
<img width="491" alt="Screen Shot 2019-03-19 at 12 58 59 PM" src="https://user-images.githubusercontent.com/6775839/54637897-fa5bd800-4a46-11e9-8ac6-b7b64ed88cda.png">

the third column can only get so small. the header for the top table has a minimum width on it pretty much because the elements of it can only get so squished together. what should happen here @matt-bullock ?

**Comment by bthaile** [comment]
Added @Chwy5

**Comment by phoebemirman** [comment]
dupe https://github.com/AugurProject/augur/issues/1530
